
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxxcpenqtpyjauvqrxip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4eGNwZW5xdHB5amF1dnFyeGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTE0MTgsImV4cCI6MjA2MDk4NzQxOH0.ANcvLoUeNqwEawb7YCcrjM9yz3B73D1lp3NMKe8W8Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
